<table height="24" border="0" cellpadding="0" cellspacing="0">
<tr> 
  <td id="mi_1" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/invoices.php" class="menuItem" onMouseOver="setClassName('mi_1','topMenuItemHigh');" onMouseOut="setClassName('mi_1','topMenuItemlow');"><?=$lang['n_invoices']?></a></td>
  <td id="mi_2" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/clients.php" class="menuItem" onMouseOver="setClassName('mi_2','topMenuItemHigh');" onMouseOut="setClassName('mi_2','topMenuItemLow');"><?=$lang['n_clients']?></a></td>
  <td id="mi_3" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/edit_invoice.php" class="menuItem" onMouseOver="setClassName('mi_3','topMenuItemHigh');" onMouseOut="setClassName('mi_3','topMenuitemlow');"><?=$lang['n_addinvoice']?></a></td>
  <td id="mi_4" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/edit_client.php" class="menuItem" onMouseOver="setClassName('mi_4','topMenuItemHigh');" onMouseOut="setClassName('mi_4','topMenuItemlow');"><?=$lang['n_addclient']?></a></td>
  <td id="mi_6" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/loader.php?f=reports" class="menuItem" onMouseOver="setClassName('mi_6','topMenuItemHigh');" onMouseOut="setClassName('mi_6','topmenuitemlow');"><?=$lang['n_reports']?></a></td>
  <td id="mi_7" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>admin/loader.php?f=admin" class="menuItem" onMouseOver="setClassName('mi_7','topMenuItemHigh');" onMouseOut="setClassName('mi_7','topMenuitemlow');"><?=$lang['n_admin']?></a></td>
  <td id="mi_5" width="100" height="24" valign="top" class="topMenuItemLow"><a href="<?=$SITE_ROOT?>logout.php" class="menuItem" onMouseOver="setClassName('mi_5','topMenuItemHigh');" onMouseOut="setClassName('mi_5','topMenuItemLow');"><?=$lang['n_logout']?></a></td>      
</tr>
</table>