<?php 
/*  ::BEGIN HEADER::
// TypicalInvoice preferences file
// Automatically generated. DO NOT EDIT THIS FILE DIRECTLY.
::END HEADER:: */
define('HTTP_ROOT',"");
define('EMAIL_ERR',"");
define('DIR_ERR',"err/");
define('DIR_EMAIL',"eml/");
$SYSTEM = array();
$SYSTEM["email"]["from"] = "";
$SYSTEM["email"]["fromName"] = "";
$SYSTEM["paygate"]["4"]["currency"] = "";
$SYSTEM["paygate"]["4"]["instId"] = "";
$SYSTEM["regional"]["currency_format"] = "$ %01.2f";
$SYSTEM["regional"]["currency_sym"] = "$";
$SYSTEM["regional"]["currency_txt"] = "USD";
$SYSTEM["regional"]["datetime"] = "d/m/y h:i:s a";
$SYSTEM["regional"]["invoicedate"] = "d/m/y";
$SYSTEM["regional"]["longdate"] = "M d, Y";
$SYSTEM["regional"]["shortdate"] = "d/m/y";
$SYSTEM["regional"]["timeoffset"] = "0";
$db_type = "";
$db_host = "";
$db_name = "";
$db_user = "";
$db_pass = "";
$db_prefix = "ti_";
$debug = "0";
$license = "";
$def_lang = "english";
$def_template = "metalblue";
$invoicerpp = "";
?>
